#!/bin/bash

printf "\n\n\n\n\n"
echo "++ ---------------------++"
docker version
docker info
which docker
echo "++ ---------------------++"
printf "\n\n"
echo "+++++ in a docker container? ++++++"
cat /proc/1/cgroup
echo "+++++ ----------------------- ++++++"
printf "\n\n\n\n\n"

cat /etc/os-release
cat /etc/lsb-release

# Test if this is possible.
systemctl daemon-reload
systemctl restart docker

systemctl show docker


# Register multiple platforms, to enable building for powerpc on non-powerpc host.
# See https://github.com/multiarch/qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
